### ISSUE TITLE
XSD 1.1 

### ISSUE THREAD

**Issue by iRyusa** [albanm/node-libxml-xsd#12]
Hi there, 

Thanks for this really cool lib, it allow us to handle the validation on github.com/mjmlio/mjml

Is there any way to use XSD 1.1, because we need  `xs:any` with an `unbounded` `maxOccurs` ?

Because we're getting a : `Entity: line 192: element element: Schemas parser error : Element '{http://www.w3.org/2001/XMLSchema}element': Invalid value for maxOccurs (must be 0 or 1).`

Thanks for the help

**Comment by iRyusa** [comment]
Thanks for the answer, I guess we'll switch for a JSON validator then !

**Comment by wking** [comment]
For what it's worth, there's a [2016-05-03 libxml bug][1] about this (no progress on the bug though).

[1]: https://bugzilla.gnome.org/show_bug.cgi?id=765936
