### ISSUE TITLE
Cannot read property validate of undefined.

### ISSUE THREAD

**Issue by alirezamirzaeiyan** [albanm/node-libxml-xsd#16]
Whenever i use libxml-xsd in nodejs environment it works correctly:

```
xsd.parseFile('schema.xsd', function (err, schema) {
    schema.validate('sample.xml', function (err, validationErrors) {

    });
});
```
But when i use same code in either electron main renderer or web renderer it gives me:
Cannot read property validate of undefined!

**Comment by albanm** [comment]
I don't know electron, but a quick search gives this: https://xwartz.gitbooks.io/electron-gitbook/content/en/tutorial/using-native-node-modules.html

node-libxml-xsd is a native module and building native modules for electron seems to be non-trivial. If someone is willing to work on a PR with either code or documentation I will be glad to accept it, but I don't have the time to do this.
