### ISSUE TITLE
Excessive depth in document: 256 use XML_PARSE_HUGE option

### ISSUE THREAD

**Issue by dardanKG** [albanm/node-libxml-xsd#17]
I have a 7mb xml file I am trying to validate. is it possible to add this option in somehow?

**Comment by albanm** [comment]
The xsd.parse method accepts a Document object parsed by libxmljs, see https://github.com/albanm/node-libxml-xsd

And it seems that libxmljs supports this option: https://github.com/libxmljs/libxmljs/issues/372

So I guess this code (not tested) should work:

```
var xsd = require('libxml-xsd');
var schema = xsd.parse(xsd.libxmljs.parseXml(xml, {huge: true}))
...
```

**Comment by dardanKG** [comment]
Thank you!
