### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by SmilinBrian** [albanm/node-libxml-xsd#20]
I could not find any licensing information for this repository, but maybe I am missing something _(wouldn't be the first time!)_

We are using this as a unit test to ensure Schema-valid XML is being generated, but foresee a possibility of using it in a product. However, we can't do that without a clear license statement.

**Comment by albanm** [comment]
There is no license file copied in the repo, but there is this in the package definition : https://github.com/albanm/node-libxml-xsd/blob/master/package.json#L26

So this is MIT, no constraint for any kind of usage.

**Comment by SmilinBrian** [comment]
OK, thank you.
