### ISSUE TITLE
Install fails on node 0.12.7 & node-gyp 3.0.2

### ISSUE THREAD

**Issue by waldekmastykarz** [albanm/node-libxml-xsd#3]
I'm having problems installing the package on:
OS X 10.10.5
node 0.12.7
node-gyp 3.0.2
npm 2.14.3

If I try to build the package from albanm/node-libxml-xsd#61ab0b4fb2b306a8cf1bd6dd2f8a6b02cad7f501 the build fails on libxmljs 0.13.0.
If I update the libxmljs dependency to 0.14.3, libxmljs builds correctly but libxml-xsd fails with the following error:

```
> node-gyp rebuild

  CXX(target) Release/obj.target/node-libxml-xsd/src/schema.o
  CXX(target) Release/obj.target/node-libxml-xsd/src/node_libxml_xsd.o
../src/node_libxml_xsd.cc:1:9: warning: 'BUILDING_NODE_EXTENSION' macro
      redefined [-Wmacro-redefined]
#define BUILDING_NODE_EXTENSION
        ^
<command line>:5:9: note: previous definition is here
#define BUILDING_NODE_EXTENSION 1
        ^
In file included from ../src/node_libxml_xsd.cc:9:
/Users/waldek/dev/node-libxml-xsd/node_modules/libxmljs/src/xml_document.h:11:28: error: 
      unknown class name 'ObjectWrap'; did you mean 'node::ObjectWrap'?
class XmlDocument : public Nan::ObjectWrap {
                           ^~~~~~~~~~~~~~~
                           node::ObjectWrap
/Users/waldek/.node-gyp/0.12.7/src/node_object_wrap.h:31:7: note: 
      'node::ObjectWrap' declared here
class ObjectWrap {
      ^
In file included from ../src/node_libxml_xsd.cc:9:
/Users/waldek/dev/node-libxml-xsd/node_modules/libxmljs/src/xml_document.h:14:12: error: 
      no type named 'Persistent' in namespace 'Nan'; did you mean
      'v8::Persistent'?
    static Nan::Persistent<v8::FunctionTemplate> constructor_template;
           ^~~~~~~~~~~~~~~
           v8::Persistent
/Users/waldek/.node-gyp/0.12.7/deps/v8/include/v8.h:561:45: note: 
      'v8::Persistent' declared here
  template<class F1, class F2> friend class Persistent;
                                            ^
In file included from ../src/node_libxml_xsd.cc:9:
/Users/waldek/dev/node-libxml-xsd/node_modules/libxmljs/src/xml_document.h:14:27: error: 
      expected member name or ';' after declaration specifiers
    static Nan::Persistent<v8::FunctionTemplate> constructor_template;
    ~~~~~~~~~~~~~~~~~~~~~~^
../src/node_libxml_xsd.cc:73:13: error: no type named 'WorkerParent' in
      namespace 'libxmljs'
  libxmljs::WorkerParent workerParent;
  ~~~~~~~~~~^
../src/node_libxml_xsd.cc:47:15: error: no member named 'WorkerSentinel' in
      namespace 'libxmljs'
    libxmljs::WorkerSentinel workerSentinel(workerParent);
    ~~~~~~~~~~^
../src/node_libxml_xsd.cc:84:5: error: no matching function for call to
      'NanAsyncQueueWorker'
    NanAsyncQueueWorker(new SchemaWorker(doc, callback));
    ^~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1946:17: note: candidate function not viable: no known
      conversion from 'SchemaWorker *' to 'NanAsyncWorker *' for 1st argument
NAN_INLINE void NanAsyncQueueWorker (NanAsyncWorker* worker) {
                ^
../src/node_libxml_xsd.cc:180:15: error: no type named 'WorkerParent' in
      namespace 'libxmljs'
    libxmljs::WorkerParent workerParent;
    ~~~~~~~~~~^
../src/node_libxml_xsd.cc:141:15: error: no member named 'WorkerSentinel' in
      namespace 'libxmljs'
    libxmljs::WorkerSentinel workerSentinel(workerParent);
    ~~~~~~~~~~^
../src/node_libxml_xsd.cc:194:5: error: no matching function for call to
      'NanAsyncQueueWorker'
    NanAsyncQueueWorker(new ValidateWorker(schema, doc, callback));
    ^~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1946:17: note: candidate function not viable: no known
      conversion from 'ValidateWorker *' to 'NanAsyncWorker *' for 1st argument
NAN_INLINE void NanAsyncQueueWorker (NanAsyncWorker* worker) {
                ^
../src/node_libxml_xsd.cc:73:26: warning: private field 'workerParent' is not
      used [-Wunused-private-field]
  libxmljs::WorkerParent workerParent;
                         ^
../src/node_libxml_xsd.cc:180:28: warning: private field 'workerParent' is not
      used [-Wunused-private-field]
    libxmljs::WorkerParent workerParent;
                           ^
3 warnings and 9 errors generated.
make: *** [Release/obj.target/node-libxml-xsd/src/node_libxml_xsd.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/waldek/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Users/waldek/.npm-packages/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/waldek/dev/node-libxml-xsd
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.2
gyp ERR! not ok 

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/Users/waldek/.npm-packages/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! libxml-xsd@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libxml-xsd@0.3.0 install script 'node-gyp rebuild'.
```

Any suggestions how to solve this issue?

**Comment by adriaanbotha** [comment]
I'm having problems installing the package on:
OS X 10.10.5
node 0.12.7
node-gyp 3.0.3
npm 2.11.3

When I try to build this, it comes back with


gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@0.12.7 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/adriaan/sream/spa-server-candelete/node-libxml-xsd/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/adriaan/sream/spa-server-candelete/node-libxml-xsd/common.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/adriaan/.node-gyp/0.12.7/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/adriaan/.node-gyp/0.12.7',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/adriaan/sream/spa-server-candelete/node-libxml-xsd',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
module.js:338
    throw err;
          ^
Error: Cannot find module 'libxmljs'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
    at [eval]:1:33
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:460:26)
    at evalScript (node.js:431:25)
    at startup (node.js:90:7)
    at node.js:814:3
gyp: Call to 'node -p -e "require('path').dirname(require.resolve('libxmljs'))"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/adriaan/sream/spa-server-candelete/node-libxml-xsd
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
